### ISSUE TITLE
expiring everything in Promotions tab

### ISSUE THREAD

**Issue by beaugunderson** [mddub/google-apps-scripts#1]
I wrote a little function to add expiration labels to everything that comes into my gmail Promotions tab:

``` js
var PROMOTION_DAYS = 7;

function addPromotionsExpiration() {
  var filters = [
    'label:Promotions',
    'in:inbox'
  ];

  for (var i = 0; i <= PROMOTION_DAYS; i++) {
    filters.push('-label:x' + i);
  }

  var threads = GmailApp.search(filters.join(' '));

  GmailApp.getUserLabelByName('x' + PROMOTION_DAYS).addToThreads(threads);
}
```

Once the labels are added the regular `stepExpiration` function takes over. I have it run every 15 minutes or so.

I went this route because you can't create a filter for things that gmail categorizes into the Promotions tab, unfortunately.

**Comment by mddub** [comment]
Thanks! Added this in 487fb83c8e37e86badb3c11ad53b0294284a70ab.
